# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 02:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preweigh_calculator', '0003_auto_20160705_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name_plural': 'Work'},
        ),
    ]
